In [1]:
import tensorflow as tf 
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))
print(tf.square(5))

#operator overloading is also supported 
print(tf.square(5)+tf.square(6))






tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(61, shape=(), dtype=int32)


In [2]:
a=tf.matmul([[1]],[[2,3]])
a

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>

In [3]:
import numpy as np
ndarray=np.ones([3,3])
print("tensorflow operations convert array to tensor automatically ")
tensor=tf.multiply(ndarray,35)
print(tensor)


tensorflow operations convert array to tensor automatically 
tf.Tensor(
[[35. 35. 35.]
 [35. 35. 35.]
 [35. 35. 35.]], shape=(3, 3), dtype=float64)


In [4]:
print(np.add(tensor,5))

[[40. 40. 40.]
 [40. 40. 40.]
 [40. 40. 40.]]


In [5]:
print(tensor.numpy())

[[35. 35. 35.]
 [35. 35. 35.]
 [35. 35. 35.]]


In [6]:
x=tf. random.uniform([3,3])

print("is there any gpu availabe ?")
print(tf.config.experimental.list_physical_devices("GPU"))
print("is the tensor on gpu #0:")
print(x.device.endswith('GPU:0'))

is there any gpu availabe ?
[]
is the tensor on gpu #0:
False


In [7]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5,6],[7,8]])

print(tf.add(a,b))
print(tf.multiply(a,b))
print(tf.matmul(a,b))   

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [8]:
print(a+b,a*b,a@b)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32) tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32) tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [9]:
#single axis indexing 
rank1=tf.constant([0,1,1,2,3,4,5,6,7,8,9])
print(rank1.numpy())

print('first value:',rank1[1].numpy())
print('second value:',rank1[2].numpy())
print('third value:',rank1[3].numpy())
print('fourth value:',rank1[4].numpy())
print('fifth value:',rank1[5].numpy())
print('Last value:',rank1[10].numpy())

[0 1 1 2 3 4 5 6 7 8 9]
first value: 1
second value: 1
third value: 2
fourth value: 3
fifth value: 4
Last value: 9


In [10]:
#example using slicing 
print('all values:',rank1[:].numpy())
print('all values after 5:',rank1[5:].numpy())
print('all values:',rank1[1:5].numpy())
print('all values reversed:',rank1[::-1].numpy())
print('all values after jumping:',rank1[::-2].numpy())

all values: [0 1 1 2 3 4 5 6 7 8 9]
all values after 5: [4 5 6 7 8 9]
all values: [1 1 2 3]
all values reversed: [9 8 7 6 5 4 3 2 1 1 0]
all values after jumping: [9 7 5 3 1 0]


In [11]:
#multi  axis indexing 
rank2=tf.constant([[1,1],[2,2],[3,3],[4,4]])
print(rank2.numpy())

print(rank2[1,1].numpy())
print(rank2[1,:].numpy())

print(rank2[1,:].numpy())

print(rank2[:,1].numpy())


[[1 1]
 [2 2]
 [3 3]
 [4 4]]
2
[2 2]
[2 2]
[1 2 3 4]


In [12]:
#rank 3 tensor 

rank3=tf.constant([[[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4]]])
print(rank3.numpy())

print()

print('2 index: ',rank3[:,:,2].numpy())

[[[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]

2 index:  [[2 2 2]]


In [13]:
#rank 4 tensor 

rank3=tf.constant([[[[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4]]]])
print(rank3.numpy())

print()

print('2 index: ',rank3[:,:,2,:].numpy())

[[[[0 1 2 3 4]
   [0 1 2 3 4]
   [0 1 2 3 4]]]]

2 index:  [[[0 1 2 3 4]]]


In [14]:
#manipulating shape 

y=tf.constant([[1],[2],[3]])
x=tf.Variable(y)
print(x.shape)

(3, 1)


In [15]:
print(tf.reshape(x,[1,3]))

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


In [16]:
#broadcast


x=tf.constant([1,2,3])
y=tf.constant([2])
z=tf.constant([2])


print(tf.multiply(x,2))

print(x*y)

print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


# variable

In [17]:
tensor=tf.constant([[1,2],[3,4]])
var=tf.Variable(tensor)


bool=tf.Variable([False,False,False,False])

com=tf.Variable([5+4j,6+1j])

print(bool)
print(com)
print(var.numpy)

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False, False])>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>
<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>>


In [18]:
#variables cant be reshape



print(' reshape is not available in variable',tf.reshape(var,([1,4])))

 reshape is not available in variable tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


In [19]:
a=tf.Variable([2,3])
a.assign([1,2])
try:
    a.assign([1,2,3])
except Exception as e:
    print(f'{type(e).__name__}: {e}')

ValueError: Cannot assign to variable Variable:0 due to variable shape (2,) and value shape (3,) are incompatible


In [20]:
a=tf.Variable([4,8])


b=tf.Variable(a)

a.assign([3,9])

print(a.numpy())
print(b.numpy())


print(a.assign_add([5,9]).numpy())
print(a.assign_sub([5,9]).numpy())

[3 9]
[4 8]
[ 8 18]
[3 9]


In [29]:
import numpy as  np 
import tensorflow as tf


a= tf.Variable(0  , name='input')
b=tf.constant(3)

mid= tf.add(a,b)

up= tf.assign(a,mid)
tg= tf.initialize_all_variables()

with tf.Session()  as sess:
    sess.run(tg)
    print(sess.run(a))
    
    for i in range(3):
        sess.run(up)
        print(sess.run(a))

AttributeError: module 'tensorflow' has no attribute 'assign'

In [1]:
# graphs

In [3]:
import tensorflow as tf 

def function_complete(x,y,b):
    x=tf.matmul(x,y)
    x=x+b
    return x
function_uses=tf.function(function_complete())

x1=tf.constant([[2,6]])
y1=tf.constant([[5,6],[7,8]])
b1=tf.constant(3.0)

function_uses(x1,y1,b1).numpy()



TypeError: function_complete() missing 3 required positional arguments: 'x', 'y', and 'b'

In [8]:
import tensorflow as tf
class model(object):
    def__init__(self):
        self.w=tf.Variable(5)
        self.b=tf.Variable(8)
        
    def __call__(self,x):
        return self.w*x+self.b
    
model=model()
assert model(3).numpy()

SyntaxError: invalid syntax (<ipython-input-8-7d39dc7969b9>, line 3)