In [2]:
import tensorflow as tf

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.35714316, -0.2695729 ,  0.06753261,  0.19130039, -0.11649287,
        -1.1780908 ,  0.32978138,  0.6067386 , -0.44066912,  0.15554662]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07011466, 0.07653148, 0.10721194, 0.12133744, 0.08919118,
        0.03085147, 0.13935941, 0.18383041, 0.06449617, 0.1170758 ]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

3.478571

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2910 - accuracy: 0.9149
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1379 - accuracy: 0.9588
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1049 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0857 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0751 - accuracy: 0.9763


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0698 - accuracy: 0.9791


[0.06982886046171188, 0.9790999889373779]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.1473991e-08, 1.3114134e-09, 2.6273572e-05, 1.9669489e-04,
        3.1803436e-12, 2.5532896e-07, 6.9575904e-13, 9.9975735e-01,
        2.0781363e-06, 1.7316273e-05],
       [8.3165519e-09, 6.8186497e-04, 9.9930072e-01, 1.5172081e-05,
        1.2832627e-14, 1.1209265e-07, 5.3402790e-08, 1.3800969e-11,
        2.1693463e-06, 5.1352497e-14],
       [1.8256215e-07, 9.9854761e-01, 2.2578367e-04, 9.9994777e-06,
        2.8884990e-05, 2.0223297e-06, 3.6130568e-06, 1.0129978e-03,
        1.6819639e-04, 6.9073036e-07],
       [9.9996495e-01, 2.7060900e-09, 8.4505182e-06, 2.4482683e-08,
        3.0383767e-08, 2.7339473e-07, 1.4123265e-05, 2.0168507e-06,
        2.7355456e-09, 1.0280657e-05],
       [1.1233410e-06, 2.2819706e-09, 1.3744246e-06, 5.5718230e-09,
        9.9933380e-01, 7.3624915e-07, 5.9408615e-07, 1.0454970e-05,
        1.4369044e-07, 6.5169838e-04]], dtype=float32)>