In [2]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import layers 

In [8]:
model=keras.Sequential([

      layers.Dense(2,activation='relu',name='layer1'),
      layers.Dense(3,activation='relu',name='layer2'),
      layers.Dense(4,name='layer3')
    ])


x= tf.ones((3,3))
y=model(x)

In [9]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.3045673 ,  0.63572997, -1.082329  , -2.0292525 ],
       [ 1.3045673 ,  0.63572997, -1.082329  , -2.0292525 ],
       [ 1.3045673 ,  0.63572997, -1.082329  , -2.0292525 ]],
      dtype=float32)>

In [10]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
model

In [18]:
model.summary

<bound method Model.summary of <tensorflow.python.keras.engine.sequential.Sequential object at 0x00000196EE7C1FD0>>