In [5]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import layers

In [10]:
model=keras.Sequential([layers.Dense(1,activation='relu',name='layer1'),layers.Dense(1,activation='relu',name='layer2'),layers.Dense(3,name='layer3')])
x=tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [12]:
model=keras.Sequential(name='sequential_model')
model.add(layers.Dense(1,activation='relu',name='layer1'))
model.add(layers.Dense(2,activation='relu',name='layer2'))
model.add(layers.Dense(3,activation='softmax',name='layer3'))

In [14]:
print(len(model.layers))

3


In [15]:
model.pop()

In [16]:
print(len(model.layers))

2
